export { Icon } from "./Icon";
export { Lazy } from "./Lazy";
export { Image } from "./Image";
export { Loader } from "./Loader";
export { Footer } from "./Footer";
export { SliderDots } from "./SliderDots";
export { SectionHeader } from "./SectionHeader";
export { ErrorBoundary } from "./ErrorBoundary";
export { SliderControls } from "./SliderControls";
